version: '3'

services:
    backend:
        image: "${DOCKER_HUB_USERNAME}/docker-swarm-workshop-backend:latest"
        ports:
            - "80:80"
        deploy:
            mode: replicated
            replicas: 4
            update_config:
                parallelism: 1
                delay: 5s


    redis:
        image: redis
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.labels.data == persistent
